# vim: set expandtab sw=2:
version: '3.3'
services:
  seed:
    container_name: seed
    image: amolabs/amotest
    networks:
      amolocal:
        ipv4_address: 192.167.10.2
    environment:
      - MONIKER=seed
      - SEEDS=
    ports:
      - "26656-26657:26656-26657"

  val1:
    depends_on:
      - seed
    container_name: val1
    image: amolabs/amotest
    networks:
      - amolocal
    environment:
      - MONIKER=val1
      - SEEDS=bdc37be128bdcdb11d2b8a9ea0c7b16f9876481d@seed:26656

  val2:
    depends_on:
      - seed
    container_name: val2
    image: amolabs/amotest
    networks:
      - amolocal
    environment:
      - MONIKER=val2
      - SEEDS=bdc37be128bdcdb11d2b8a9ea0c7b16f9876481d@seed:26656

  pdb0:
    container_name: pdb0
    image: paust-db
    networks:
      amolocal:
        ipv4_address: 192.167.10.10
    environment:
      - ID=0
    volumes:
      - /tmp/pdb0:/tendermint:Z

  #rep1:
  #  container_name: rep1
  #  build: .

  #rep2:
  #  container_name: rep2
  #  build: .

networks:
  amolocal:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/24
