# vim: set expandtab sw=2:
# amolabs/amoabci CircleCI 2.0 configuration file
#
# - executor: docker (amo-client image)
# - build (bootstrap)
#    - docker build image
#    - docker-compose create (without mounting volumes)
#    - docker copy config files from host to container
# - test
#    - run test_script
# - deploy
#
# DO NOT USE TABS FOR INDENTATION!!!
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/amolabs/amoabci
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "docker build image"
          command: make docker
      - run:
          name: "docker-compose create: creating dummy containers"
          command: docker-compose create
      - run:
          name: "docker copy config files from host to container"
          command: echo "dummy1"
  test:
    docker:
      - image: circleci/classic:latest
    steps:
      - run:
        command: echo "dummy"
    
  deploy:
    docker:
      - image: circleci/classic:latest
    steps:
      - run:
        command: echo "dummy"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

    

