# vim: set expandtab sw=2:

# <peeer dependency>
# - val1 <- seed
# - seed <- val2, val3, val4, val5, val6

version: '3.3'
services:
  testcli:
    container_name: testcli
    image: amolabs/testcli
    networks:
      - amolocal
    
  seed:
    container_name: seed
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=seed
      - PEERS=__val1_addr__@val1:26656
    volumes:
      - seedconfig:/tendermint
      - /amo

  val1:
    container_name: val1
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=val1
      - PEERS=
    volumes:
      - val1config:/tendermint
      - /amo

  val2:
    container_name: val2
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=val2
      - PEERS=__seed_addr__@seed:26656
    volumes:
      - val2config:/tendermint
      - /amo

  val3:
    container_name: val3
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=val3
      - PEERS=__seed_addr__@seed:26656
    volumes:
      - val3config:/tendermint
      - /amo

  val4:
    container_name: val4
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=val4
      - PEERS=__seed_addr__@seed:26656
    volumes:
      - val4config:/tendermint
      - /amo

  val5:
    container_name: val5
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=val5
      - PEERS=__seed_addr__@seed:26656
    volumes:
      - val5config:/tendermint
      - /amo

  val6:
    container_name: val6
    image: amolabs/amod
    networks:
      - amolocal
    environment:
      - MONIKER=val6
      - PEERS=__seed_addr__@seed:26656
    volumes:
      - val6config:/tendermint
      - /amo

networks:
  amolocal:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/24

volumes:
  seedconfig:
  val1config:
  val2config:
  val3config:
  val4config:
  val5config:
  val6config:
