name: build-deploy
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set env var for RELEASE_VERSION
      run: echo "::set-env name=RELEASE_VERSION::${GITHUB_REF:10}"

    - name: Set env var for ASSET
      run: echo "::set-env name=ASSET::amod-${RELEASE_VERSION/v/''}-linux-x86_64.tar.gz"

    - name: Unit Test
      run: make test

    - name: Install cleveldb
      run: sudo apt install libleveldb-dev 

    - name: Build
      run: make TARGET=linux build_c

    - name: Wrap
      run: tar -czf ${{ env.ASSET }} amod

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }} release
          draft: true 
          prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/gzip
      
